### ISSUE TITLE
RTICK time scale / units

### ISSUE THREAD

**Issue by cmr** [Arke64/ArkeOS#36]
Currently RTICK is specified to be in nanoseconds. Instead, I'd prefer it to be just a scalar, with configuration in the processor device space giving how many ns per tick there is.

**Comment by Arke64** [comment]
Is this a read-only configuration in the address space that lets you know what the processor says for ns per tick or a user-writable one? If user-writable, what are you imaging?

**Comment by Arke64** [comment]
Talked offline. Will have two read-only processor address space fields that return the time units per unit in RTICK and another that specifies the time unit (ns, us, ps, etc)

**Comment by Arke64** [comment]
Fixed in 1a421f069a534a2ac565530612c92000dc37f663
